language: android

jdk:
 - oraclejdk8

android:
  components:
    - build-tools-21.1.2
    - android-21

script:
  - ./gradlew clean check

branches:
  except:
    - gh-pages

cache:
  directories:
    - $HOME/.gradle